spring.application.name=notification-service

server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/notification_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:notification_service}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:notification_service_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.core.base-url=${CORE_SERVICE_URL:http://localhost:8080}
app.internal-api-key=${INTERNAL_API_KEY}

app.jwt.secret=${JWT_SECRET}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:mission_control}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:mission_control_dev}