services:

  postgres:
    image: postgres:18
    container_name: mission-control-postgres
    environment:
      POSTGRES_DB: mission_control
      POSTGRES_USER: mission_control
      POSTGRES_PASSWORD: mission_control_dev
    ports:
      - "5432:5432"
    volumes:
      - mission_control_postgres_data:/var/lib/postgresql

  telemetry-postgres:
    image: postgres:18
    container_name: telemetry-service-postgres
    environment:
      POSTGRES_DB: telemetry_service
      POSTGRES_USER: telemetry_service
      POSTGRES_PASSWORD: telemetry_service_dev
    ports:
      - "5433:5432"
    volumes:
      - telemetry_service_postgres_data:/var/lib/postgresql

  alert-postgres:
    image: postgres:18
    container_name: alert-service-postgres
    environment:
      POSTGRES_DB: alert_service
      POSTGRES_USER: alert_service
      POSTGRES_PASSWORD: alert_service_dev
    ports:
      - "5434:5432"
    volumes:
      - alert_service_postgres_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4-management
    container_name: mission-control-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mission_control
      RABBITMQ_DEFAULT_PASS: mission_control_dev
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mission_control_postgres_data:
  telemetry_service_postgres_data:
  alert_service_postgres_data: