services:

  postgres:
    image: postgres:18
    container_name: mission-control-postgres
    environment:
      POSTGRES_DB: mission_control
      POSTGRES_USER: mission_control
      POSTGRES_PASSWORD: mission_control_dev
    ports:
      - "5432:5432"
    volumes:
      - mission_control_postgres_data:/var/lib/postgresql

  telemetry-postgres:
    image: postgres:18
    container_name: telemetry-service-postgres
    environment:
      POSTGRES_DB: telemetry_service
      POSTGRES_USER: telemetry_service
      POSTGRES_PASSWORD: telemetry_service_dev
    ports:
      - "5433:5432"
    volumes:
      - telemetry_service_postgres_data:/var/lib/postgresql

volumes:
  mission_control_postgres_data:
  telemetry_service_postgres_data: