CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    telemetry_record_id BIGINT,
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    message VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ
);

CREATE INDEX idx_alerts_vehicle_created_at
    ON alerts (vehicle_id, created_at DESC);

CREATE INDEX idx_alerts_vehicle_type_status
    ON alerts (vehicle_id, type, status);