spring.application.name=mission-control

spring.datasource.url=jdbc:postgresql://localhost:5432/mission_control
spring.datasource.username=mission_control
spring.datasource.password=mission_control_dev

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true