spring.application.name=telemetry-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/telemetry_service
spring.datasource.username=telemetry_service
spring.datasource.password=telemetry_service_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true