CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    alert_id BIGINT NOT NULL,

    message VARCHAR(255) NOT NULL,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_notifications_alert
        FOREIGN KEY (alert_id)
        REFERENCES alerts(id)
);

CREATE INDEX idx_notifications_user_created_at
    ON notifications (user_id, created_at DESC);